// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXuzOzfLBaOufd3s0vqc7DjAQXdryrFsc',
    appId: '1:1066335163948:web:831abfc0081cf86b702389',
    messagingSenderId: '1066335163948',
    projectId: 'green-life-c0153',
    authDomain: 'green-life-c0153.firebaseapp.com',
    storageBucket: 'green-life-c0153.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD33g0_EdVOsTLMKklHjB_gY3RhEM0wnnE',
    appId: '1:1066335163948:android:0388f5b95c50b07b702389',
    messagingSenderId: '1066335163948',
    projectId: 'green-life-c0153',
    storageBucket: 'green-life-c0153.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrnaz2PtrFJlR5rgYalr4wlp9nifs_Mh4',
    appId: '1:1066335163948:ios:b5d09d0c64e84a99702389',
    messagingSenderId: '1066335163948',
    projectId: 'green-life-c0153',
    storageBucket: 'green-life-c0153.firebasestorage.app',
    iosBundleId: 'com.example.greenlife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrnaz2PtrFJlR5rgYalr4wlp9nifs_Mh4',
    appId: '1:1066335163948:ios:b5d09d0c64e84a99702389',
    messagingSenderId: '1066335163948',
    projectId: 'green-life-c0153',
    storageBucket: 'green-life-c0153.firebasestorage.app',
    iosBundleId: 'com.example.greenlife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXuzOzfLBaOufd3s0vqc7DjAQXdryrFsc',
    appId: '1:1066335163948:web:136531e5b55c7542702389',
    messagingSenderId: '1066335163948',
    projectId: 'green-life-c0153',
    authDomain: 'green-life-c0153.firebaseapp.com',
    storageBucket: 'green-life-c0153.firebasestorage.app',
  );
}
